/*
#  LattesXtractor V1.1
#  Copyright 2019: Richard William Valdivia
#  E-mail: rwvaldivia@yahoo.com.br
#
#  Link do Repostório de Pesquisa
#  http://repositorio.unifesp.br/handle/11600/57106
#  
#  Download da Dissertação Mestrado
#  http://repositorio.unifesp.br/bitstream/handle/11600/57106/Dissertacao_Richard%20William%20Valdivia.pdf?sequence=1&isAllowed=y
#
#  Este programa é um software livre; você pode redistribui-lo e/ou 
#  modifica-lo dentro dos termos da Licença Pública Geral GNU como 
#  publicada pela Fundação do Software Livre (FSF); na versão 2 da 
#  Licença, ou (na sua opinião) qualquer versão.
#
#  Este programa é distribuído na esperança que possa ser util, 
#  mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
#  MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
#  Licença Pública Geral GNU para maiores detalhes.
#
#  Você deve ter recebido uma cópia da Licença Pública Geral GNU
#  junto com este programa, se não, escreva para a Fundação do Software
#  Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
*/
package br.xtractor.gui.LattesStractorMainGui;

import br.xtractor.helper.SharedMemoryHelper;
import br.xtractor.lattes.app.LattesXtractor;
import br.xtractor.lattes.core.CurriculoLattes;
import br.xtractor.lattes.vo.IdentificacaoVO;
import br.xtractor.lattes.vo.Pesquisador;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author richard.valdivia
 */
public class LattesXtractorGui extends javax.swing.JFrame {

    /**
     * Creates new form LattesXtractorGui
     */
    public File lastDirectoryOpened = null;
    private static SharedMemoryHelper sharedMemory;
    private String STR_READ_REGISTER = "Total de Registros lidos: ";
    
    public LattesXtractorGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesquisador = new javax.swing.JTable();
        lblNomeAplicacao = new javax.swing.JLabel();
        btnCarregaDadosXml = new javax.swing.JButton();
        btnGrafoPrefuse = new javax.swing.JButton();
        btnRedeColaboracaoGEFX = new javax.swing.JButton();
        lblReadRegister = new javax.swing.JLabel();
        ckboxHiddenNames = new javax.swing.JCheckBox();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuItemXmlRedeColaboracao = new javax.swing.JMenuItem();
        mnuItemAnimacaoRede = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPesquisador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "No.", "ID Lattes", "Pesquisador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPesquisador);

        lblNomeAplicacao.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblNomeAplicacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeAplicacao.setText("LattesXtractor");

        btnCarregaDadosXml.setText("Carregar dados do XML");
        btnCarregaDadosXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregaDadosXmlActionPerformed(evt);
            }
        });

        btnGrafoPrefuse.setText("Lista de Pesquisadores");
        btnGrafoPrefuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafoPrefuseActionPerformed(evt);
            }
        });

        btnRedeColaboracaoGEFX.setText("Exportar para XML Gephi");
        btnRedeColaboracaoGEFX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeColaboracaoGEFXActionPerformed(evt);
            }
        });

        lblReadRegister.setText("Total de registros lidos: 0");

        ckboxHiddenNames.setText("Abreviar nomes");
        ckboxHiddenNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckboxHiddenNamesActionPerformed(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        mnuItemXmlRedeColaboracao.setMnemonic('o');
        mnuItemXmlRedeColaboracao.setText("Exportar para XML Gephi");
        mnuItemXmlRedeColaboracao.setToolTipText("");
        mnuItemXmlRedeColaboracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemXmlRedeColaboracaoActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItemXmlRedeColaboracao);

        mnuItemAnimacaoRede.setMnemonic('o');
        mnuItemAnimacaoRede.setText("Lista de Pesquisadores");
        mnuItemAnimacaoRede.setToolTipText("");
        mnuItemAnimacaoRede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAnimacaoRedeActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItemAnimacaoRede);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeAplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCarregaDadosXml)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGrafoPrefuse)
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReadRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ckboxHiddenNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRedeColaboracaoGEFX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNomeAplicacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregaDadosXml)
                    .addComponent(btnGrafoPrefuse)
                    .addComponent(btnRedeColaboracaoGEFX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReadRegister)
                    .addComponent(ckboxHiddenNames))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    public File getLastDirectoryOpened() {
        if (this.lastDirectoryOpened == null || "".equals(this.lastDirectoryOpened)){
            lastDirectoryOpened = FileSystemView.getFileSystemView().getHomeDirectory();
        }
        
        return lastDirectoryOpened;
    }
    

    public void setLastDirectoryOpened(File lastDirectoryOpened) {
        this.lastDirectoryOpened = lastDirectoryOpened;
    }
    
    private void btnCarregaDadosXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregaDadosXmlActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(this.getLastDirectoryOpened());
        jfc.setDialogTitle("Selecione o arquivo XML");
        jfc.setAcceptAllFileFilterUsed(false);

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos XML", "xml");
        jfc.addChoosableFileFilter(filter);

        int returnValue = jfc.showOpenDialog(null);
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            String path = jfc.getSelectedFile().getPath();
            File pathFile = new File(path);
            this.setLastDirectoryOpened(pathFile);
            LattesXtractor xtractor = new LattesXtractor();
            CurriculoLattes cl = null;
            try {
                cl = xtractor.extractCurriculoLattes(path);
            } catch (Exception io) {
                JOptionPane.showMessageDialog(null, "Arquivo XML invalido");
                io.printStackTrace();
                return;
            }
            
            if (cl != null) {
                
                List<Pesquisador> pesquisadores = cl.getPesquisador();
                LattesXtractorGui.sharedMemory.setCurriculoLattes(cl);
                DefaultTableModel model = new DefaultTableModel();
                
                model.addColumn("No.");
                model.addColumn("ID Lattes");
                model.addColumn("Pesquisador");
                
                String numero;
                String idPesquisador;
                String nomePesquisador;
                
                for(int k = 0; k < (pesquisadores.size()); k++){
                    
                    Pesquisador p = pesquisadores.get(k);
                    IdentificacaoVO identificacao = p.getIdentificacao();
                    
                    Vector row = new Vector();
                    
                    numero          = "" + (k + 1);
                    idPesquisador   = p.getId();
                    nomePesquisador = identificacao.getNomeInicial();
                    
                    row.add(numero);
                    row.add(idPesquisador);
                    row.add(nomePesquisador);
                    
                    model.addRow(row);
                    
                }

                tblPesquisador.setModel(model);
                this.lblReadRegister.setText(STR_READ_REGISTER + pesquisadores.size());
                
//                tblPesquisador.setModel(new javax.swing.table.DefaultTableModel(
//                        new Object[][]{
//                             {"" + (++i), "123456", "Richard William Valdivia"},
//                             {"" + (++i), "123456", "Richard William Valdivia"},
//                             {"" + (++i), "123456", "Richard William Valdivia"},
//                             {"" + (++i), "123456", "Richard William Valdivia"}
//                        },
//                        new String[]{
//                            "No.", "ID Lattes", "Pesquisador"
//                        }
//                ) {
//                    boolean[] canEdit = new boolean[]{
//                        false, false
//                    };
//
//                    public boolean isCellEditable(int rowIndex, int columnIndex) {
//                        return canEdit[columnIndex];
//                    }
//                });
            }

        }

    }//GEN-LAST:event_btnCarregaDadosXmlActionPerformed

    private void mnuItemXmlRedeColaboracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemXmlRedeColaboracaoActionPerformed
        this.btnRedeColaboracaoGEFXActionPerformed(evt);
    }//GEN-LAST:event_mnuItemXmlRedeColaboracaoActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void mnuItemAnimacaoRedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAnimacaoRedeActionPerformed
       this.btnGrafoPrefuseActionPerformed(evt);
    }//GEN-LAST:event_mnuItemAnimacaoRedeActionPerformed

    private void callPrefuseDisplayGraph(){
        LattesXtractor extractor = new LattesXtractor();
        
        if (SharedMemoryHelper.getCurriculoLattes()!= null) {
            try {
                extractor.displayLattesGraph(SharedMemoryHelper.getCurriculoLattes());
            } catch(IOException io){
                io.printStackTrace();
            }
        }
    }
    private void btnGrafoPrefuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafoPrefuseActionPerformed
        // TODO add your handling code here:
        if (SharedMemoryHelper.getCurriculoLattes() == null){
            JOptionPane.showMessageDialog(null, "Leia o arquivo xml antes de executar essa operação.");
            return;
        }
        
        
        this.callPrefuseDisplayGraph();
          
    }//GEN-LAST:event_btnGrafoPrefuseActionPerformed

    private void btnRedeColaboracaoGEFXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeColaboracaoGEFXActionPerformed
        // TODO add your handling code here:
        
        if (SharedMemoryHelper.getCurriculoLattes() == null){
            JOptionPane.showMessageDialog(null, "Leia o arquivo xml antes de executar essa operação.");
            return;
        }
        
        JFileChooser jfc = new JFileChooser(this.getLastDirectoryOpened());
        jfc.setDialogTitle("Selecione o arquivo XML");
        jfc.setAcceptAllFileFilterUsed(false);

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos GEXF", "gexf");
        jfc.addChoosableFileFilter(filter);
        
        if (jfc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            String path = jfc.getSelectedFile().getPath();
            path += ".gexf";
            LattesXtractor xtractor = new LattesXtractor();
            CurriculoLattes cl = SharedMemoryHelper.getCurriculoLattes();
            boolean hiddenNames = !ckboxHiddenNames.isSelected();
            xtractor.generateGephXml(cl, path, hiddenNames);
        }
        
    }//GEN-LAST:event_btnRedeColaboracaoGEFXActionPerformed

    private void ckboxHiddenNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckboxHiddenNamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckboxHiddenNamesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LattesXtractorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LattesXtractorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LattesXtractorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LattesXtractorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LattesXtractorGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnCarregaDadosXml;
    private javax.swing.JButton btnGrafoPrefuse;
    private javax.swing.JButton btnRedeColaboracaoGEFX;
    private javax.swing.JCheckBox ckboxHiddenNames;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeAplicacao;
    private javax.swing.JLabel lblReadRegister;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuItemAnimacaoRede;
    private javax.swing.JMenuItem mnuItemXmlRedeColaboracao;
    private javax.swing.JTable tblPesquisador;
    // End of variables declaration//GEN-END:variables

}
